server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/rates
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/rates
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration

fiat:
  api:
    url: http://localhost:8080/fiat-currency-rates
    key: secret-key

crypto:
  api:
    url: http://localhost:8080/crypto-currency-rates

logging:
  level:
    currency.rate.service: debug
